# Generated by Django 2.0.4 on 2019-02-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverymail',
            name='student',
        ),
        migrations.DeleteModel(
            name='RecoveryMail',
        ),
    ]
