# Generated by Django 2.1.1 on 2019-02-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyadvisor', '0003_auto_20190220_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesser',
            name='popularitet',
            field=models.IntegerField(default=0),
        ),
    ]
