# Generated by Django 2.1.7 on 2019-02-27 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyadvisor', '0004_interesser_popularitet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studieforslag',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
