# Generated by Django 2.0.4 on 2019-03-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190326_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
