# Generated by Django 2.2 on 2019-04-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_is_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='participents',
            new_name='participants',
        ),
    ]
